name: Publish Mutation Report
on:
  push:
    branches:
      - main
jobs:
  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install Stryker
        run: dotnet tool install -g dotnet-stryker
      - name: Run Stryker
        run: dotnet-stryker --reporter html --project-file Bank.Domain.Tests/Bank.Domain.Tests.csproj
        working-directory: Bank
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./StrykerOutput 