# nuget
name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore Bank/Bank.sln
      - name: Build
        run: dotnet build Bank/Bank.sln --configuration Release
      - name: Pack
        run: dotnet pack Bank/Bank.Domain/Bank.Domain.csproj --configuration Release /p:PackageVersion=2024123456
      - name: Publish to GitHub Packages
        run: dotnet nuget push Bank/Bank.Domain/bin/Release/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Bank/Bank.Domain/bin/Release/*.nupkg

# nuget 